### ISSUE TITLE
Scaling on smaller displays

### ISSUE THREAD

**Issue by fossdd** [SoongNoonien/plattenalbum#120]
would be nice if plattenalbum would fit on smaller displays like mobile phones, so that they could be supported by mobile user interfaces like Phosh.

**Comment by SoongNoonien** [comment]
The most recent commit makes some progress on this. The artist list on the left will now be hidden if there is not enough space. This reduced the minimum window width from 800px to 620px. With libadwaita 1.6 and [bottom sheets](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.BottomSheet.html) I should also be able to make the playlist hide on narrow window sizes.

**Comment by fossdd** [comment]
Great, thanks for the work!

**Comment by doronbehar** [comment]
Thanks for updating @SoongNoonien . This indeed helps. For the inpatients, here's a screenshot of the smallest screen I managed to get to:

![image](https://github.com/SoongNoonien/plattenalbum/assets/10998835/d15302fb-5686-4f9c-a3b9-8cbc9a465c9c)

It is 742 × 602 pixels . I wish we could get down to a width of 480 pixels :pray:.

**Comment by SoongNoonien** [comment]
> It is 742 × 602 pixels

How did you measure this? Without any HIDPI scaling the minimum size is 620x480, which corresponds exactly to your screenshot (proportion wise).

> I wish we could get down to a width of 480 pixels 🙏.

I think this should be possible with these bottom sheets.

**Comment by doronbehar** [comment]
> How did you measure this?

Oh Indeed my measurement included some empty pixels in the background that Gnome's screenshot includes from some reason. Still though, if I understand correctly, the most minimal width now is 620 pixels, and not 480 pixels, which makes it still not fit to my little project :). My screen size is close to a 480x480 square. 

The bottom sheets you are referring to are not something that the user can modify right? The link seems to point to API.. If not I assume you wanted to point us to how to help our selves solve this issue?

**Comment by SoongNoonien** [comment]
> The bottom sheets you are referring to are not something that the user can modify right?

No, these are just a new UI element coming in the next libadwaita version.

> The link seems to point to API.. If not I assume you wanted to point us to how to help our selves solve this issue?

No, I just gave the link that you can see how they look like.

**Comment by 1peter10** [comment]
Great app, I hope it's okay if I chime in here regarding phones. For phones, going to 620 px width is not enough.
To make it adaptive, here's the recommendation from [GNOME HIG](https://developer.gnome.org/hig/guidelines/adaptive.html)

> Apps that are appropriate for a phone form factor should scale down to 360×294px.

This is in line with device specs, I've [collected some specs](https://linuxphoneapps.org/docs/resources/developer-information/#hardware-specs-to-consider) on a project of mine. Since I am not aware of any other mpd frontend working well on mobile, it would be really great to have Plattenalbum become adaptive!

I am happy to help with testing and feedback!

**Comment by SoongNoonien** [comment]
> Great app, I hope it's okay if I chime in here regarding phones.

Yes, of course!

> To make it adaptive, here's the recommendation from [GNOME HIG](https://developer.gnome.org/hig/guidelines/adaptive.html)...

I'm aware of that ;-) With libadwaita 1.6 being right around the corner now I'm confident that I can make this happen soon. As I've mentioned above I need some features of version 1.6 like the bottom sheets to implement full adaptiveness. At least a minimal width of 360px wont be a problem then. But a minimum height of 294px might get a bit tricky. I suppose this small height comes form some multitasking features of the phosh shell?

> I am happy to help with testing and feedback!

That is good the here! Because as I've mentioned on multiple occasions I only have a normal workstation with a keyboard and a mouse, not even a laptop with a touchpad. At least I have a 4k screen so I can test HiDPI support :-)

**Comment by SoongNoonien** [comment]
Ok, I've gotten around to using the new bottom sheets to decrease the minimum width to 360px. The minimal height is still at 480px. Currently the sidebar on the right (respectively the bottom sheet) is the limiting factor here. I'll see what I can do about that. Note that this requires libadwaita 1.6.0, so you have to get it from somewhere. For the Arch/AUR users there is already a binary package of the 1.6.0rc in the gnome-unstable repo. For the flatpak users there is the gnome master runtime which can be obtained [here](https://wiki.gnome.org/Apps/Nightly).

**Comment by SoongNoonien** [comment]
> But a minimum height of 294px might get a bit tricky. I suppose this small height comes form some multitasking features of the phosh shell?

Ok, I get it now. It's because of the landscape mode, I missed that when I first read it.

**Comment by 1peter10** [comment]
Yes, the 294px is landscape, and if it is ineed from Phosh shell, there should be more space available now, as Phosh's bottom bar is less space hungry these days. That said - don't worry about landscape too much, it's a stretch goal at best ;-) 

I have build the app from master, and it's fine now in initial testing (with local mpd and three songs) - I still need to set up mpd somewhere on my network with my music library (as I had years ago, but hardware failure ended that back then)  to fully test it. So far: Very nice, well done, thank you!

I'll report back if I have some suggestions for improvement :smile:
