### ISSUE TITLE
Scrollbar does not hide in album list

### ISSUE THREAD

**Issue by rien333** [SoongNoonien/plattenalbum#142]
Opening a series of (fairly minor) issues, since I see you're trying to make plattenalbum become a Gnome Circle app!

# Description

The scrollbar that is shown in an artist's album list will never hide. Instead, it just blinks, which may indicate that it in fact does try to disappear, but can never fully do so for some reason (see video below).

In other Gnome apps (e.g. Files), the scrollbar will hide automatically after a period of inactivity. 

Could be a GTK bug, but I haven't noticed this problem in other Gnome apps. 

# To reproduce

1. Go to an artist for which you have a lot of albums in your collection, so that a scrollbar will be shown. 
2. Hover your pointer over an album.

# Video

https://github.com/user-attachments/assets/11bfc264-e19b-4ca4-924a-52cbbc5a916e

# Version info

* Plattenalbum: latest commit (this issue is much older though)
* Gnome: 46
* Distro: Arch Linux

**Comment by SoongNoonien** [comment]
Sorry, but I can't reproduce this over here. It disappears just fine. Can you reproduce this on another machine?

**Comment by rien333** [comment]
> Can you reproduce this on another machine?

I tried to on my work laptop running Arch Linux on Windows through WSL while using X11. The scrollbar disappears just fine. 

So could be wayland-related somehow (which I run on my main machine), but probably not plattenalbum-related.

**Comment by SoongNoonien** [comment]
I think I know how to reproduce this now. Apparently a song needs to be playing for this to happen. Can you confirm? It seems to be caused by the updating seekbar which somehow resets the timeout every time it moves. And just for reference this is not limited to the albums list in the middle. At least over here it is observable in the artists list and the playlist as well.

**Comment by rien333** [comment]
Ah yes that's it! Good catch.

**Comment by SoongNoonien** [comment]
> Ah yes that's it!

Nice, but why did you reopen the issue? It's still on GTK's side. I can fix it over here. When looking at the right applications you can find this bug now also in other GTK apps. Take for example [Amberol](https://apps.gnome.org/Amberol/). When a song is playing the scrollbar won't disappear as well. As Amberol only updates its progressbar every second the "blinking" of the scrollbar is just a bit slower.
I'm fairly certain that similar behavior can be observed in any GTK4 app which periodically updates its GUI due to a progressbar for example.

**Comment by rien333** [comment]
Sorry! Re-opening was done without any thought. Good that you found the same behavior in other apps, though.
