### ISSUE TITLE
[Feature Request] Would it be possible to include MPD in the flatpak?

### ISSUE THREAD

**Issue by Froggy232** [SoongNoonien/plattenalbum#153]
Hi,
First, thanks you for your software!
I try to deploy mpd in podman locally, it launch and plattenalbum connect to it, but it has no sound.
I have search on internet and haven't found any solution.
Maybe it would be possible to include MPD in the flatpak container, while still leaving the option to connect to another mpd instance of course. This way, Plattenalbum would be able to read the local music library without any dependencies, I think it would be interesting for a lot of users, who usually have their musics in their `~/Music` folder I think.
Also, would it be possible to add an instance chooser in the upper left corner, like some apps does (like pods as example)? This way, user could switch from included instance to a remote one in one click, I would be personally very interested in this feature but I don't know if many users would.
Thanks for your soft by the way, it looks very great!
Best regards

**Comment by rien333** [comment]
> I try to deploy mpd in podman locally, it launch and plattenalbum connect to it, but it has no sound.

So, to double check, plattenalbum actually finds the mpd instance you've deployed in podman, but there is no sound coming from your speakers/audio devices?

Could you maybe share the configuration of the mpd instance you've deployed with podman? That way, we can all try to reproduce your problem locally.

**Comment by Froggy232** [comment]
Hi,
Yes, it's exactly that, mpd in podman run well and detect all my libraries, Plattenalbum can connect to it through 127.0.0.1 and everything seems to work well except that I have no sound.
I don't know if the sound should came out from MPD or Plattenalbum, if it's from MPD I very probably have a problem with my podman configuration.
I will join my .quadlet file of MPD container here : [https://privatebin.alrhome.net/?b0567228dcbdceb7#DJ5kAmE8TH51zZ4nCYx3j44A86pihjcZHn6P1spuBMB1 ](MPD Quadlet File)
I have try with your mpd.conf file, and also without to try with the stock default value of the podman container. The last `mpd.conf` file I have try is here : [MPD Config File]( https://privatebin.alrhome.net/?14aa7c4b46cc6c34#GHTr5izQ76stLFVMMZ9XBhbSgB6y4ZDFBs817BCBYWit)
I have try to modify it so it correspond of the container layout, but it haven't work either.
Thanks a lot for your help, I would be very glad if I could use this software.
Have a nice day!

**Comment by Froggy232** [comment]
I just try with a `music_folder` entry in the `mpd.conf` file, and I have new error message now : 

```
exception: Failed to enable output "Music" (pulse); pa_context_connect() has failed: Connection refused
exception: Failed to enable output "Music" (pulse); pa_context_connect() has failed: Connection refused
player: problems opening audio device while playing "Dub Inc/Futur/1.01. Allons leur dire.flac"
```

I use Fedora Silverblue 41, so probably I have to adapt the file to pipewire?
Thanks again, I will continue to investigate.

**Comment by SoongNoonien** [comment]
Hi!

> Maybe it would be possible to include MPD in the flatpak container, while still leaving the option to connect to another mpd instance of course. This way, Plattenalbum would be able to read the local music library without any dependencies, I think it would be interesting for a lot of users, who usually have their musics in their ~/Music folder I think.

This has been request some time ago in #113. Unfortunately I forgot to answer it for a long time until I found it again recently. But I decided to wait until someone requests this again.
While I get your point and see the possible advantages I don't want to do it. MPD is a complex program with many dependencies and build options. I don't want to maintain something that big in a package while most major distributions already do a great job at it. Inside a flatpak this would even be harder since I'd need to build (and keep up to date) most of the dependencies as well.

>  I try to deploy mpd in podman locally, it launch and plattenalbum connect to it, but it has no sound.

> Yes, it's exactly that, mpd in podman run well and detect all my libraries, Plattenalbum can connect to it through 127.0.0.1 and everything seems to work well except that I have no sound.

> I don't know if the sound should came out from MPD or Plattenalbum, if it's from MPD I very probably have a problem with my podman configuration.

The sound is played by MPD. Plattenalbum just controls what MPD should play. So the sound is played on the device MPD runs on.

> I have try with your mpd.conf file, and also without to try with the stock default value of the podman container. The last mpd.conf file I have try is here : [MPD Config File](https://privatebin.alrhome.net/?14aa7c4b46cc6c34#GHTr5izQ76stLFVMMZ9XBhbSgB6y4ZDFBs817BCBYWit)

I suppose you mean the config from the wiki or the initial guide respectively? This assumes that your music is located in your XDG-Music-Folder. So possibly `~/Music`.

> I just try with a music_folder entry in the mpd.conf file, and I have new error message now :

Ok, good. At least your collection seems to be indexed now.

> `exception: Failed to enable output "Music" (pulse); pa_context_connect() has failed: Connection refused`

This suggests that your sound server isn't running.

> I use Fedora Silverblue 41, so probably I have to adapt the file to pipewire?

No, this shouldn't be necessary. I'm using pipewire as well and have a similar config. Actually pipewire implements a pulseaudio interface. So all programs compatible with pulseaudio are still compatible with pipewire.

**Comment by Froggy232** [comment]
I understand, thanks you a lot, I will investigate mpd in podman, maybe a selinux problem also.
Anyway, thanks for your help, it was very precious,
Have a nice day
