### ISSUE TITLE
New fallback cover handling

### ISSUE THREAD

**Issue by Richjn** [SoongNoonien/plattenalbum#157]
@SoongNoonien  I'm using now a simple gray gradient as a fallback cover.

Sorry but I think the gray box is ugly as.
I know this is a personal preference thing but I was quite happy with the old CD icon even if it is depreciated i.e the icon could be shipped with plattenalbum if themes drop support for it.

Edited to clarify

Richard

**Comment by rien333** [comment]
Agreed that this somewhat of a step back, though I really appreciate all the other album cover changes!

The CD icon looks much more like a fallback cover, especially because it has transparency, which album covers never have. The newer one, on the other hand, would be difficult differentiatie someone's gray artistic vision! 😉

Additionally, the old one looks more Gnome-y. Placeholder images tend to be monochrome and symbolic (cf. https://developer.gnome.org/hig/patterns/feedback/placeholders.html). The HIG also states that they should either be monochrome or colorful — I feel like a gray gradient sits somewhere awkwardly in between those two.

**Comment by SoongNoonien** [comment]
The problem is that this isn't a placeholder page. So I don't think https://developer.gnome.org/hig/patterns/feedback/placeholders.html helps us here.

I came up with the gray gradient as a metaphor for an empty image. Using an icon in full size is not ideal as they are usually meant to be displayed at much smaller sizes. Also the full color CD icon has weak contrast with the light theme (at least the Adwaita icon). I could imagine displaying a Vinly icon (probably the one from the app icon) at a fixed size. But I'm not sure if this looks any better. I personally quite like that the gradient fill the whole cover area.

**Comment by Richjn** [comment]
> The problem is that this isn't a placeholder page. 
When first opening plattenalbum I feel this area is very much a candidate for a placeholder image and although I didn't make it very clear in my comment it is the use of the gray box here that bothers me.

Is it possible to use the CD icon at start up then something else as a cover fallback ?

**Comment by SoongNoonien** [comment]
Ok, now I see. I assumed you were talking about the fallback covers in the browser

> Is it possible to use the CD icon at start up then something else as a cover fallback ?

Yes, this is possible. And the CD icon (or probably some other icon) could indeed be a status page.

**Comment by Richjn** [comment]
Just a thought but if a suitable icon is not currently available for the cover fallback image maybe just add text saying "Cover Unavailable" (or similar) rather than use an icon at all ?

**Comment by SoongNoonien** [comment]
With a placeholder page (for the main cover) there would always be both.  But the actual fallback cover needs to be an image or a solid color.

**Comment by Richjn** [comment]
I promise not to bombard you with these but maybe Unicode U+2754❔

**Comment by SoongNoonien** [comment]
What do you think about hiding the cover altogether when nothing is playing? In the same way I'm already hiding the seek bar.

**Comment by Richjn** [comment]
I think hiding the cover when nothing is playing would be better than showing the missing cover gray panel although I do feel showing the CD as a placeholder adds a touch of "polish"

I'm being selfish here but I have 100% artwork coverage so I will never see the gray panel but as a general comment I would rather the cover was hidden in the absence of artwork rather than show the gray in all circumstances.

I understand the potential issue of using the current CD image where it was not intended to be scaled but I have a 4K monitor and even with plattenalbum maximised it still looks ok to me but maybe I'm missing the point as I'm no developer.

**Comment by Richjn** [comment]
Closing as fixed
